apiVersion: v1
kind: Service
metadata:
  name: logstash-discovery
  labels:
    component: elk
    role: logstash
spec:
  selector:
    component: elk
    role: logstash
  ports:
#  - name: transport
#    port: 9600
#    protocol: TCP
  - name: http
    port: 8100
    protocol: TCP
  type: NodePort
