apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    component: elk
    role: kibana
spec:
  selector:
    component: elk
    role: kibana
  ports:
  - name: http
    port: 5601
  type: NodePort