# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Custom config borrowed from Pires: https://github.com/pires/docker-elasticsearch-kubernetes

cluster:
  name: ${CLUSTER_NAME:FLAGON}
  initial_master_nodes: ["${INITIAL_MASTER_NODES:elasticsearch}"]

node:
  name: ${NODE_NAME:elasticsearch}

network.host: ${NETWORK_HOST:0.0.0.0}

path:
  data: /usr/share/elasticsearch/data
  logs: /usr/share/elasticsearch/log

bootstrap:
  memory_lock: ${MEMORY_LOCK}

http:
  compression: true
  cors:
    enabled: ${HTTP_CORS_ENABLE:true}
    allow-origin: ${HTTP_CORS_ALLOW_ORIGIN:"*"}

# Prevent the "split brain" by configuring the majority of nodes (total number of nodes / 2 + 1):
discovery:
    seed_hosts: ["${DISCOVERY_SERVICE:0.0.0.0}"]

## X-Pack settings
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html
#
xpack.license.self_generated.type: trial
xpack.security.enabled: false

##
## TLS configuration
## See instructions from README to enable.
##

## Communications between nodes in a cluster
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-tls.html#tls-transport
#
#xpack.security.transport.ssl.enabled: true
#xpack.security.transport.ssl.verification_mode: certificate
#xpack.security.transport.ssl.certificate_authorities: [ ca.crt ]
#xpack.security.transport.ssl.certificate: elasticsearch.crt
#xpack.security.transport.ssl.key: elasticsearch.key

## HTTP client communications
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-tls.html#tls-http
#
#xpack.security.http.ssl.enabled: true
#xpack.security.http.ssl.certificate_authorities: [ ca.crt ]
#xpack.security.http.ssl.certificate: elasticsearch.crt
#xpack.security.http.ssl.key: elasticsearch.key