apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: quickstart
spec:
  count: 1
  elasticsearchRefs:
    - name: quickstart
      clusterName: qs
  version: 8.12.0
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          http {
            codec => "json"
            port => 8100
            response_headers => { 
              "Access-Control-Allow-Origin" => "*" 
              "Access-Control-Allow-Headers" => "*"
            }
          }
        }

        filter {
          mutate {
            remove_field => [ "message", "@version", "headers"]
          }

          grok {
              match => [ "useraleVersion", "(?<major_ver>\d+).(?<minor_ver>\d+)(.(?<patch_ver>\d+))?" ]
              match => [ "toolVersion", "(?<tool_major_ver>\d+).(?<tool_minor_ver>\d+)(.(?<tool_patch_ver>\d+))?" ]
          }
        }

        output {
          elasticsearch {
            hosts => [ "${QS_ES_HOSTS}" ]
            user => "${QS_ES_USER}"
            password => "${QS_ES_PASSWORD}"
            ssl_certificate_authorities => "${QS_ES_SSL_CERTIFICATE_AUTHORITY}"
            index => "userale"
          }
        }
  services:
    - name: http
      service:
        spec:
          type: NodePort
          ports:
            - port: 8100
              name: "http"
              protocol: TCP
              targetPort: 8100