#----------------------------- PostgreSQL Module -----------------------------
- module: postgresql
  metricsets: ["database", "activity"]
  period: 10s
  enabled: true

  # The host must be passed as PostgreSQL URL. Example:
  # postgres://localhost:5432?sslmode=disable
  # The available parameters are documented here:
  # https://godoc.org/github.com/lib/pq#hdr-Connection_String_Parameters
  hosts: ["${POSTGRESQL_URL}"]

  # Username to use when connecting to PostgreSQL. Empty by default.
  username: "${POSTGRESQL_USERNAME}"

  # Password to use when connecting to PostgreSQL. Empty by default.
  password: "${POSTGRESQL_PASSWORD}"