metricbeat.config.modules:

  # Glob pattern for configuration reloading
  path: ${path.config}/modules.d/*.yml

  # Period on which files under path should be checked for changes
  reload.period: 30s

  # Set to true to enable config reloading
  reload.enabled: true

# Maximum amount of time to randomly delay the start of a metricset. Use 0 to
# disable startup delay.
metricbeat.max_start_delay: 10s 

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_URL}"]

setup.dashboards.enabled: true

setup.kibana:
  host: "${KIBANA_URL}"

logging.to_files: false