#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Userale CI test suite
run-name: ${{ github.actor }} running Userale CI test suite

on:
  push:
    branches:
      - master
    paths:
      - products/userale/**
  pull_request:
    branches:
      - master
    paths:
      - products/userale/**

defaults:
  run:
    working-directory: ./products/userale

jobs:
  pre-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm v10
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm i

      - name: Format 
        run: pnpm format

      - name: Lint 
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        # See active and security support for Node.js at https://endoflife.date/nodejs
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm v10
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm i

      - name: Install Playwright Browsers
        run: |
          npx playwright install --with-deps
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Build
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          pnpm build

      - name: Test
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          pnpm test

      # TODO: add automatic release notes
      # TODO: add cronjobs for automatically triggering new release candidates
